# Generated by Django 5.2 on 2025-05-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='amount',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='apptoken',
            new_name='contactperson',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='fcm',
            new_name='trn',
        ),
        migrations.RemoveField(
            model_name='user',
            name='whatsapp',
        ),
        migrations.AddField(
            model_name='user',
            name='attachement',
            field=models.FileField(blank=True, null=True, upload_to='user'),
        ),
    ]
