# Generated by Django 5.2 on 2025-05-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='unique_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
