# Generated by Django 5.2 on 2025-05-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0004_bookings_unique_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_airport', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('iata_code', models.CharField(blank=True, max_length=10, null=True)),
                ('alpha_2', models.CharField(max_length=5)),
                ('alpha_3', models.CharField(max_length=5)),
                ('un_code', models.IntegerField()),
            ],
        ),
    ]
