# Generated by Django 5.2 on 2025-05-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0005_airports'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airlines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iata', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(max_length=255)),
                ('country_or_region', models.CharField(max_length=100)),
            ],
        ),
    ]
