# Generated by Django 5.2 on 2025-05-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0007_accountledgers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agenttype',
            field=models.TextField(null=True),
        ),
    ]
