# Generated by Django 5.2 on 2025-05-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0008_user_agenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='passportnumber',
            field=models.TextField(blank=True, null=True),
        ),
    ]
