# Generated by Django 5.2 on 2025-05-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0010_cashreceipts'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountledgers',
            name='pnr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
