# Generated by Django 5.2 on 2025-05-25 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0011_accountledgers_pnr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refunds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.TextField(blank=True, null=True)),
                ('netamount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('grossamount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('markup', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='superadmin.bookings')),
            ],
        ),
    ]
