# Generated by Django 5.2 on 2025-05-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0013_staffs_delete_banner_remove_universities_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='staff'),
        ),
    ]
