# Generated by Django 5.2 on 2025-05-29 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0014_staffs_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletUPdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactiontype', models.TextField(blank=True, null=True)),
                ('referencenumber', models.TextField(blank=True, null=True)),
                ('bankdetails', models.TextField(blank=True, null=True)),
                ('transactiondate', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='wallet')),
                ('is_verify', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
