# Generated by Django 5.2 on 2025-05-31 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0019_user_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cashreceipts',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='refunds',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='walletupdates',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
