# Generated by Django 5.2 on 2025-06-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0020_bookings_is_delete_cashreceipts_is_delete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refunds',
            name='refundamount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
