# Generated by Django 5.2 on 2025-06-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0021_refunds_refundamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='refunds',
            name='is_verify',
            field=models.BooleanField(default=False),
        ),
    ]
