# Generated by Django 5.2 on 2025-06-01 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0023_leadsdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.TextField(blank=True, null=True)),
                ('servicetype', models.TextField(blank=True, null=True)),
                ('fromairport', models.TextField(blank=True, null=True)),
                ('toairport', models.TextField(blank=True, null=True)),
                ('departuredate', models.DateField(blank=True, null=True)),
                ('airline', models.TextField(blank=True, null=True)),
                ('pnr', models.TextField(blank=True, null=True)),
                ('passportnumber', models.TextField(blank=True, null=True)),
                ('ticketnumber', models.TextField(blank=True, null=True)),
                ('passengername', models.TextField(blank=True, null=True)),
                ('servicedescription', models.TextField(blank=True, null=True)),
                ('netamount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('grossamount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('markup', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sales', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
