# Generated by Django 5.2 on 2025-06-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0024_sales'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.TextField(blank=True, null=True)),
                ('transactiontype', models.TextField(blank=True, null=True)),
                ('pnr', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('debit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('credit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
