# Generated by Django 5.2 on 2025-06-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0025_salesledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesCashReceipts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.TextField(blank=True, null=True)),
                ('paymenttype', models.TextField(blank=True, null=True)),
                ('receivedfrom', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
