# Generated by Django 5.2 on 2025-06-02 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0027_salescashreceipts_createdby'),
    ]

    operations = [
        migrations.AddField(
            model_name='salescashreceipts',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='superadmin.sales'),
        ),
    ]
