# Generated by Django 5.2 on 2025-06-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0028_salescashreceipts_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='previllages',
            name='acsess',
        ),
        migrations.RemoveField(
            model_name='previllages',
            name='is_active',
        ),
        migrations.AddField(
            model_name='previllages',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='previllages',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='previllages',
            name='write',
            field=models.BooleanField(default=False),
        ),
    ]
