# Generated by Django 5.2 on 2025-06-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0029_remove_previllages_acsess_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='attachement',
            field=models.FileField(blank=True, null=True, upload_to='staff'),
        ),
        migrations.AddField(
            model_name='staffs',
            name='password',
            field=models.TextField(blank=True, null=True),
        ),
    ]
