# Generated by Django 5.2 on 2025-06-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0031_stafflogins'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafflogins',
            name='is_absent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stafflogins',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
