# Generated by Django 5.2 on 2025-06-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0032_stafflogins_is_absent_stafflogins_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafflogins',
            name='approvedby',
            field=models.TextField(blank=True, null=True),
        ),
    ]
