# Generated by Django 5.2 on 2025-06-04 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0033_stafflogins_approvedby'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffTimings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intime', models.TextField(blank=True, null=True)),
                ('outtime', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='superadmin.stafflogins')),
            ],
        ),
    ]
