# Generated by Django 5.2 on 2025-06-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0034_stafftimings'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafflogins',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
