# Generated by Django 5.2 on 2025-06-08 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0035_stafflogins_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletupdates',
            name='createdby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_wallet', to=settings.AUTH_USER_MODEL),
        ),
    ]
