# Generated by Django 5.2 on 2025-06-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0036_walletupdates_createdby'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletupdates',
            name='unique_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
