# Generated by Django 5.2 on 2025-06-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0037_walletupdates_unique_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginImageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banenrimage', models.ImageField(blank=True, null=True, upload_to='home')),
                ('slider1', models.ImageField(blank=True, null=True, upload_to='home')),
                ('slider2', models.ImageField(blank=True, null=True, upload_to='home')),
                ('slider3', models.ImageField(blank=True, null=True, upload_to='home')),
                ('slider4', models.ImageField(blank=True, null=True, upload_to='home')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
